'use client';
import { useState } from 'react';
import ImageUploader from './ImageUploader';import ModeSelector from './ModeSelector';import ColorSelector from './ColorSelector';import RepeatSelector from './RepeatSelector';import GenerationProgress from './GenerationProgress';import DesignGrid from './DesignGrid';
const toDataUrl=(f:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(f)});
export default function CreateStudio(){const [file,setFile]=useState<File|null>(null);const [reference,setReference]=useState('');const [mode,setMode]=useState('Modern');const [color,setColor]=useState('Original Colors');const [repeat,setRepeat]=useState('Seamless Repeat');const [high,setHigh]=useState(false);const [images,setImages]=useState<string[]>([]);const [analysis,setAnalysis]=useState<any>(null);const [loading,setLoading]=useState(false);const [stage,setStage]=useState('');const [error,setError]=useState('');
const run=async(selectedFile=file)=>{if(!selectedFile)return;setError('');setLoading(true);try{const ref=await toDataUrl(selectedFile);setReference(ref);setStage('Analyzing your textile design…');const fd=new FormData();fd.append('image',selectedFile);fd.append('mode',mode);fd.append('color',color);fd.append('repeat',repeat);const a=await fetch('/api/analyze',{method:'POST',body:fd});const aj=await a.json();if(!a.ok)throw new Error(aj.error);setAnalysis(aj.analysis);setStage('Creating 6 unique variations…');const g=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis:aj.analysis,options:{mode,color,repeat,highResolution:high},reference:ref})});const gj=await g.json();if(!g.ok)throw new Error(gj.error);setImages(gj.images);setStage('Preparing your designs…');setTimeout(()=>setLoading(false),350);}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Please try again.');setLoading(false)}};
const handleFile=async(f:File|null)=>{setFile(f);setImages([]);setAnalysis(null);if(f){const ref=await toDataUrl(f);setReference(ref);run(f)}else setReference('')};
const regenerateOne=async(i:number)=>{if(!reference)return;setError('');try{const r=await fetch('/api/regenerate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference,instruction:`Create a new textile design variation #${i+1}. Mode ${mode}; color ${color}; repeat ${repeat}. Preserve the reference design language but substantially change motif arrangement, composition and rhythm.`})});const j=await r.json();if(!r.ok)throw new Error(j.error);setImages(old=>old.map((x,n)=>n===i?j.image:x));}catch(e){setError(e instanceof Error?e.message:'Could not regenerate this design.')}};
const downloadAll=async()=>{const r=await fetch('/api/download-all',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images})});if(!r.ok){setError('Could not create ZIP.');return}const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='textile-designs-6.zip';a.click()};
return <div className="workspace"><aside className="panel"><h3>01 · Reference</h3><ImageUploader file={file} onChange={handleFile}/><ModeSelector value={mode} onChange={setMode}/><ColorSelector value={color} onChange={setColor}/><RepeatSelector value={repeat} onChange={setRepeat}/><label className="chip" style={{display:'inline-flex',marginTop:18,alignItems:'center',gap:7}}><input type="checkbox" checked={high} onChange={e=>setHigh(e.target.checked)}/> HIGH RESOLUTION</label><button className="generate" disabled={!file||loading} onClick={()=>run()}>{loading?'Generating…':'Generate 6 Designs'}</button>{error&&<p style={{color:'#9b3f35',fontSize:12,lineHeight:1.5}}>{error}</p>}</aside><section className="results-panel"><div className="section-head"><div><span className="eyebrow">02 · Output</span><h2>Six new directions.</h2></div>{images.length===6&&<button className="secondary" onClick={downloadAll}>Download All 6</button>}</div>{loading?<GenerationProgress stage={stage}/>:images.length===6?<><div className="comparison"><div><span className="eyebrow">Original</span><img className="preview" src={reference} alt="Original reference"/></div><div><span className="eyebrow">AI Design 01</span><img className="preview" src={images[0]} alt="First AI variation"/></div></div><div style={{display:'flex',gap:8,justifyContent:'flex-end',marginBottom:15}}><button className="primary" onClick={()=>run()}>REGENERATE 6 DESIGNS</button></div><DesignGrid images={images} onRegenerate={regenerateOne}/></>:<div className="empty"><strong>Upload one image to begin automatically.</strong><p>The analysis starts as soon as a valid reference is selected.</p></div>}{analysis&&<details style={{marginTop:24,color:'#766b63',fontSize:12}}><summary>View AI analysis</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(analysis,null,2)}</pre></details>}</section></div>}
